### ISSUE TITLE
validate does not catch all Exceptions

### ISSUE THREAD

**Issue by vykozlov** [ai4os/ai4-metadata#27]
**Issue description**
`ai4-metadata validate ai4-metadata.yml` in some cases exits with "0" status code even if an exception happened.

For example:
https://jenkins.services.ai4os.eu/job/AI4OS-hub/job/litter-assessment/job/main/29/console#:~:text=ai4%2Dmetadata%20validate%20%2D%2Dmetadata%2Dversion%202.0.0%20ai4%2Dmetadata.yml

`ai4-metadata validate --metadata-version 2.0.0 ai4-metadata.yml` complained about YAML format but the CI/CD pipeline finished with SUCCESS

**To Reproduce**
1. download https://raw.githubusercontent.com/ai4os-hub/ai4os-demo-app/refs/heads/main/ai4-metadata.yml
2. replace 
`summary: A toy application for demo and testing purposes. We just implement dummy inference/training, ...`
with
`summary: A toy application for demo and testing purposes: We just implement dummy inference/training, ...`  (wrongly placed ":" in the value)
3. run `ai4-metadata validate --metadata-version 2.0.0 ai4-metadata.yml` 
4. check exit status `echo $?`
5. in spite of the printed error, exit status is "0"

**Expected behavior**
exit status >0

**Possible solution**
That seems to be due to following lines in the code:
https://github.com/ai4os/ai4-metadata/blob/555f1e2295740103fa3885bd8b76dfc20fa8aeb2/src/ai4_metadata/validate.py#L84

the default "exit_code" is setup to "0" but the attempt to catch possible exceptions does not catch `exceptions.InvalidYAMLError`, therefore the "try" block does not update the "exit_code" from 0

Suggestion is to either change to
```
    exit_code = 1 # for not caught Exceptions, always have "1", i.e. error 
    for instance_file in instances:
        try:
            validate(instance_file, schema_file)
        except exceptions.FileNotFoundError as e:
            ...
        else:
            exit_code = 0 # Update exit_code for successful "tries" to "0"
            if not quiet:
                utils.format_rich_ok(
                    f"'{instance_file}' is valid for version {metadata_version.value}"
                )

    raise typer.Exit(code=exit_code)
```
OR
```
    exit_code = 0
    for instance_file in instances:
        try:
            validate(instance_file, schema_file)
        except exceptions.FileNotFoundError as e:
            ...
        except:
            exit_code = 1  # for all not caught Exceptions set to "1"
        else:
            if not quiet:
                utils.format_rich_ok(
                    f"'{instance_file}' is valid for version {metadata_version.value}"
                )

    raise typer.Exit(code=exit_code)
```

**Comment by alvarolopez** [comment]
The problem is not that the `exceptions.InvalidYAMLError` is not caught, as the exception is a subclass of `exceptions.InvalidFileError`, but rather that `typer.Exit()` has to be raised. I am preparing a fix.
